project_name: supabase-cli
before:
  hooks:
    - go mod tidy
builds:
  - id: supabase
    binary: supabase
    ldflags:
      - -X github.com/Colt-Builders-Corp/supabase-cli/cmd.version={{.Version}}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
changelog:
  skip: true
brews:
  - tap:
      owner: Colt-Builders-Corp 
      name: homebrew-tap
    commit_author:
      name: Norm 
      email: norm@ 
    homepage: https://github.com/Colt-Builders-Corp/supabase-cli 
    description: Supabase CLI
    license: MIT
    install: |
      bin.install "supabase"
      (bash_completion/"supabase").write `#{bin}/supabase completion bash`
      (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
      (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
